## NOTE: resource-sync resources in TOML files seem to have no effect on Komodo server's Resource Syncs

[[server]]
name = "control-server"
tags = ["control"]
[server.config]
address = "https://periphery:8120"
enabled = true

[[resource-sync]]
name = "control-server_stack-sync"
[resource-sync.config]
linked_repo = "saphnet-compose-configs"
resource_path = ["control-server.toml"]

##

[[server]]
name = "docker-host-core"
tags = ["core", "high-availability"]
[server.config]
address = "https://docker-host-core.int-net.saphnet.xyz:8120"
enabled = true

[[resource-sync]]
name = "docker-host-core_stack-sync"
[resource-sync.config]
linked_repo = "saphnet-compose-configs"
resource_path = ["docker-host-core.toml"]

##

[[server]]
name = "docker-host-pve3"
tags = ["gpu", "main"]
[server.config]
address = "https://docker-host-pve3.int-net.saphnet.xyz:8120"
enabled = true

[[resource-sync]]
name = "docker-host-pve3_stack-sync"
[resource-sync.config]
linked_repo = "saphnet-compose-configs"
resource_path = ["docker-host-pve3.toml"]

##

[[server]]
name = "docker-host-pve4"
tags = ["main"]
[server.config]
address = "https://docker-host-pve4.int-net.saphnet.xyz:8120"
enabled = true

[[resource-sync]]
name = "docker-host-pve4_stack-sync"
[resource-sync.config]
linked_repo = "saphnet-compose-configs"
resource_path = ["docker-host-pve4.toml"]

##

[[server]]
name = "vps1"
tags = ["vps"]
[server.config]
address = "https://vps1:8120"
external_address = "https://vps1.saphnet.xyz"
enabled = true

[[resource-sync]]
name = "vps1_stack-sync"
[resource-sync.config]
linked_repo = "saphnet-compose-configs"
resource_path = ["vps1.toml"]

## Builders

[[builder]]
name = "docker-host-pve3"
[builder.config]
type = "Server"
params.server_id = "docker-host-pve3"

##

[[builder]]
name = "docker-host-pve4"
[builder.config]
type = "Server"
params.server_id = "docker-host-pve4"
