[[action]]
name = "saphnet-update-tailscale-addresses"
description = """
Automatically updates the values of TAILSCALE_IP address with the Tailscale IP addresses of all Servers.

Arguments:
- variableBase - The base name of the variables being updated (by default, "TAILSCALE_IP_", which will lead to names like "TAILSCALE_IP_CONTROL")
- targetServer - The name of the Server that will run the necessary Terminal (this Server needs access to Tailscale's MagicDNS)
- terminalName - The name of the (ephemeral) Terminal to open
- servers - An array of objects that represent each Server
  - hostname - The Tailscale hostname of the Server
  - varSuffix - The short name of the Server to use as a suffix for its corresponding variable name
"""
tags = ["iac"]
[action.config]
schedule_format = "Cron"
schedule_enabled = false
file_contents = """
for (const server of ARGS.servers) {
  let resolvedIp = "";

  console.log(`Checking server ${server.hostname}...`);
  // awk SHOULD make sure we only get one line (and no trailing newlines either)...
  await komodo.execute_server_terminal({
    server: ARGS.targetServer,
    terminal: ARGS.terminalName,
    command: `getent ahostsv4 ${server.hostname} | awk '{printf $1; exit}'`,
    init: { command: "bash", recreate: "Always" },
  }, {
    onLine: (line) => {
      if (line.trim()) {
        console.log(`> ${line}`);
        resolvedIp = line.trim();
      }
    },
    onFinish: (code) => {
      if (code !== "0") {
        console.log(`Encountered an error while checking ${server.hostname}, code ${code}`);
      } else {
        console.log(`Success checking ${server.hostname}!`);
      }
    }
  });

  // To avoid clutter
  await komodo.write("DeleteTerminal", {
    target: { 
      type: "Server", 
      params: { server: ARGS.targetServer } 
    },
    terminal: ARGS.terminalName
  });

  if (resolvedIp) {
    let variableName = `${ARGS.variableBase}${server.varSuffix}`.toUpperCase();

    // Check if variable exists, this is clunky but it hopefully is O(1),
    // depending on the back-end implementation
    // (There doesn't exactly exist a clean "CheckVariableExists" struct)
    try {
      await komodo.read("GetVariable", { name: `${variableName}` });
    } catch (error) {
      if (
        typeof error === 'object' &&
        error !== null &&
        error.status === 500 &&
        typeof error.result?.error === 'string' &&
        error.result.error.includes("no variable found with given name")
      ) {
        console.log(`Variable ${variableName} does not exist, creating variable...`)
        await komodo.write("CreateVariable", {
          name: `${variableName}`
        });
        console.log(`Variable ${variableName} created!`);
      } else {
        console.error("An unexpected error occurred:", error);
      }
    }
    
    console.log(`Updating variable ${variableName} to ${resolvedIp}`);
    await komodo.write("UpdateVariableValue", {
      name: `${variableName}`,
      value: resolvedIp,
    });
  } else {
    console.error(`Failed to resolve IP for ${server.hostname}`);
  }

  console.log();
}
"""
arguments_format = "json"
arguments = """
{
  "variableBase": "TAILSCALE_IP_",
  "targetServer": "control-server",
  "terminalName": "saphnet-update-tailscale-addresses",
  "servers": [
    { "hostname": "control-server", "varSuffix": "CONTROL" },
    { "hostname": "docker-host-core", "varSuffix": "CORE" },
    { "hostname": "docker-host-pve3", "varSuffix": "PVE3" },
    { "hostname": "docker-host-pve4", "varSuffix": "PVE4" },
    { "hostname": "vps1", "varSuffix": "VPS1" }
  ]
}
"""
