## Non-secret variables

## NOTE: TAILSCALE_IP_ variables are taken care of by the saphnet-update-tailscale-addresses action!

[[variable]]
name = "CERTBOT_EMAIL"
value = "homelab@saphnet.xyz"
is_secret = false

[[variable]]
name = "SAPHNET_S3_SERVER_REGION"
value = "garage"
is_secret = false

[[variable]]
name = "SAPHNET_S3_SERVER_ENDPOINT"
value = "https://s3.nas1.int.saphnet.xyz"
is_secret = false

[[variable]]
name = "TIMEZONE"
value = "America/Los_Angeles"
is_secret = false
